---
fixtures:
  repositories:
    openvoxdb:
      repo: "https://github.com/voxpupuli/puppet-openvoxdb.git"
      ref: "b32a25f"
    openvoxview:
      repo: "https://github.com/voxpupuli/puppet-openvoxview.git"
      ref: "v1.3.0"
  forge_modules:
    inifile:
      repo: puppetlabs/inifile
      ref: 6.4.1
    stdlib:
      repo: puppetlabs/stdlib
      ref: 9.7.0
    chrony:
      repo: puppet/chrony
      ref: 5.0.0
    firewall:
      repo: puppetlabs/firewall
      ref: 8.5.0
    sudo:
      repo: saz/sudo
      ref: 9.0.2
    concat:
      repo: puppetlabs/concat
      ref: 9.1.0
    yum:
      repo: puppet/yum
      ref: 8.1.1
    apt:
      repo: puppetlabs/apt
      ref: 11.3.2
    postgresql:
      repo: puppetlabs/postgresql
      ref: 10.6.3
    archive:
      repo: puppet/archive
      ref: 8.1.0
    systemd:
      repo: puppet/systemd
      ref: 8.3.1
    cron_core:
      repo: puppetlabs/cron_core
      ref: 2.0.2
    yumrepo_core:
      repo: puppetlabs/yumrepo_core
      ref: 3.0.1
  symlinks:
    profile: "#{source_dir}"
