source 'https://rubygems.org'

group :test do
  gem 'puppet', ENV.fetch('PUPPET_GEM_VERSION', '>= 0'), require: false
  gem 'puppet_metadata', '~> 3.4', require: false
  gem 'puppetlabs_spec_helper', '>= 2.16.0', '< 7', require: false
  gem 'rubocop', require: false
end

group :system_tests do
  gem 'beaker', require: false
  gem 'beaker-docker', require: false
  gem 'beaker-rspec', '>= 8.0', require: false
end

