name: CI

on:
  pull_request:
  push:
    branches:
      - production

concurrency:
  group: ${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  test:
    name: Puppet 8
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: site-modules/profile
    steps:
      - uses: actions/checkout@v4

      - name: Read Ruby version
        id: ruby-version
        run: echo "version=$(cat .ruby-version)" >> "$GITHUB_OUTPUT"
        working-directory: .

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ steps.ruby-version.outputs.version }}
          bundler-cache: true
          working-directory: site-modules/profile

      - name: Validate
        run: bundle exec rake validate lint check

      - name: Run tests
        run: bundle exec rake parallel_spec
